services:
  app:
    restart: unless-stopped
    build:
      context: .
    ports:
      - mode: ingress
        target: 8080
        published: 8080
    deploy:
      resources:
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]